apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: workshop
spec:
  ingressClassName: traefik
  rules:
  - host: workshop.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 80
